dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - cmake .
  - cmake --build . -- -j2 

notifications:
  email:
    on_success: never
    on_failure: always
